"""grant consumption

Revision ID: 03b46c72ab8a
Revises: 6a5d644b25a2
Erstellt: 2026-08-19 15:10:01.437872
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "03b46c72ab8a"
down_revision: str | None = "6a5d644b25a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tool_invocations", sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_invocations", "consumed_at")
    # ### end Alembic commands ###
