"""initial schema

Revision ID: 07215b957d0f
Revises:
Erstellt: 2026-08-18 16:39:06.271150
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "07215b957d0f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector muss vor allen Vector-Spalten existieren. Autogenerate kennt
    # Extensions nicht — daher hier ausdrücklich.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugins",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugins")),
        sa.UniqueConstraint("name", name=op.f("uq_plugins_name")),
    )
    op.create_index(op.f("ix_plugins_created_at"), "plugins", ["created_at"], unique=False)
    op.create_table(
        "scopes",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("default_mode", sa.String(length=16), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "default_mode IN ('deny','confirm','allow')", name=op.f("ck_scopes_default_mode_valid")
        ),
        sa.CheckConstraint(
            "risk_level IN ('low','medium','high','critical')",
            name=op.f("ck_scopes_risk_level_valid"),
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_scopes")),
    )
    op.create_table(
        "system_health",
        sa.Column("component", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ok','degraded','down','unknown')",
            name=op.f("ck_system_health_status_valid"),
        ),
        sa.PrimaryKeyConstraint("component", name=op.f("pk_system_health")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("locale", sa.String(length=10), server_default="de-DE", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Europe/Berlin", nullable=False),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "daily_budget_eur",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("5.00"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource", sa.String(length=255), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("prev_hash", sa.LargeBinary(), nullable=True),
        sa.Column("entry_hash", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_occurred_at"), "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "automations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("trigger_type", sa.String(length=24), nullable=False),
        sa.Column("trigger_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("action", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "allowed_scopes",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "requires_confirmation", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trigger_type IN ('cron','once','calendar_event','email_match','webhook','state_change')",
            name=op.f("ck_automations_trigger_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_automations_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automations")),
    )
    op.create_index(op.f("ix_automations_created_at"), "automations", ["created_at"], unique=False)
    op.create_index(
        "ix_automations_next_fire",
        "automations",
        ["next_fire_at"],
        unique=False,
        postgresql_where=sa.text("enabled"),
    )
    op.create_table(
        "connected_accounts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("display_label", sa.String(length=255), nullable=False),
        sa.Column("granted_scopes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','expired','revoked','error')",
            name=op.f("ck_connected_accounts_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_connected_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connected_accounts")),
        sa.UniqueConstraint("user_id", "provider", "external_id", name="uq_account_identity"),
    )
    op.create_index(
        op.f("ix_connected_accounts_created_at"), "connected_accounts", ["created_at"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_upto", sa.UUID(), nullable=True),
        sa.Column("private_mode", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('voice','text','proactive','automation')",
            name=op.f("ck_conversations_channel_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_created_at"), "conversations", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("data_class", sa.String(length=2), server_default="P2", nullable=False),
        sa.Column("is_untrusted", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_documents_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("user_id", "content_hash", name="uq_documents_user_hash"),
    )
    op.create_index(op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False)
    op.create_table(
        "memories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("structured", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_class", sa.String(length=2), server_default="P2", nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), server_default=sa.text("1.0"), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="candidate", nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column("importance", sa.Float(), server_default=sa.text("0.5"), nullable=False),
        sa.Column("access_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('german', content)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_class IN ('P0','P1','P2','P3')", name=op.f("ck_memories_data_class_valid")
        ),
        sa.CheckConstraint(
            "kind IN ('semantic_fact','preference','episodic','entity','procedure')",
            name=op.f("ck_memories_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('candidate','active','superseded','rejected')",
            name=op.f("ck_memories_status_valid"),
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name=op.f("ck_memories_confidence_range")),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["memories.id"],
            name=op.f("fk_memories_superseded_by_memories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memories_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(op.f("ix_memories_created_at"), "memories", ["created_at"], unique=False)
    op.create_index(
        "ix_memories_retention",
        "memories",
        ["retention_until"],
        unique=False,
        postgresql_where=sa.text("retention_until IS NOT NULL"),
    )
    op.create_index(
        "ix_memories_search_tsv", "memories", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_memories_user_kind_status", "memories", ["user_id", "kind", "status"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column(
            "constraints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('deny','confirm','allow')", name=op.f("ck_permissions_mode_valid")
        ),
        sa.ForeignKeyConstraint(
            ["scope"], ["scopes.name"], name=op.f("fk_permissions_scope_scopes")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_permissions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("user_id", "scope", name="uq_permissions_user_scope"),
    )
    op.create_index(op.f("ix_permissions_created_at"), "permissions", ["created_at"], unique=False)
    op.create_table(
        "plugin_permissions",
        sa.Column("plugin_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("granted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugins.id"],
            name=op.f("fk_plugin_permissions_plugin_id_plugins"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scope"], ["scopes.name"], name=op.f("fk_plugin_permissions_scope_scopes")
        ),
        sa.PrimaryKeyConstraint("plugin_id", "scope", name=op.f("pk_plugin_permissions")),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("project", sa.String(length=120), nullable=True),
        sa.Column("external_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open','in_progress','done','cancelled')",
            name=op.f("ck_tasks_status_valid"),
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_tasks_priority_range")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tasks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_created_at"), "tasks", ["created_at"], unique=False)
    op.create_index(op.f("ix_tasks_due_at"), "tasks", ["due_at"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_table(
        "webauthn_credentials",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("device_label", sa.String(length=120), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_webauthn_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webauthn_credentials")),
        sa.UniqueConstraint("credential_id", name=op.f("uq_webauthn_credentials_credential_id")),
    )
    op.create_index(
        op.f("ix_webauthn_credentials_created_at"),
        "webauthn_credentials",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_user_id"), "webauthn_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("heading_path", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('german', content)", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "seq", name="uq_chunks_doc_seq"),
    )
    op.create_index(
        "ix_chunks_search_tsv",
        "document_chunks",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "memory_embeddings",
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_embeddings_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("memory_id", "model", name=op.f("pk_memory_embeddings")),
    )
    op.create_index(
        "ix_memory_embeddings_hnsw",
        "memory_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_parts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_class", sa.String(length=2), server_default="P1", nullable=False),
        sa.Column("is_tainted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("model_used", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_class IN ('P0','P1','P2','P3')", name=op.f("ck_messages_data_class_valid")
        ),
        sa.CheckConstraint(
            "role IN ('user','assistant','tool','system')", name=op.f("ck_messages_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "oauth_credentials",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("wrapped_dek", sa.LargeBinary(), nullable=False),
        sa.Column("kek_id", sa.String(length=64), nullable=False),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["connected_accounts.id"],
            name=op.f("fk_oauth_credentials_account_id_connected_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_credentials")),
    )
    op.create_index(
        op.f("ix_oauth_credentials_account_id"), "oauth_credentials", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_credentials_created_at"), "oauth_credentials", ["created_at"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("trigger", sa.String(length=16), server_default="user", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="queued", nullable=False),
        sa.Column("classification", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("routing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("taint_level", sa.String(length=10), server_default="clean", nullable=False),
        sa.Column("data_class", sa.String(length=2), server_default="P1", nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "usage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "data_class IN ('P0','P1','P2','P3')", name=op.f("ck_runs_data_class_valid")
        ),
        sa.CheckConstraint("taint_level IN ('clean','tainted')", name=op.f("ck_runs_taint_valid")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_runs_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(
        "ix_runs_resumable",
        "runs",
        ["status"],
        unique=False,
        postgresql_where=sa.text(
            "status IN ('queued','planning','executing','awaiting_confirmation')"
        ),
    )
    op.create_index(op.f("ix_runs_trace_id"), "runs", ["trace_id"], unique=False)
    op.create_index("ix_runs_user_started", "runs", ["user_id", "started_at"], unique=False)
    op.create_table(
        "chunk_embeddings",
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_chunk_embeddings_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chunk_id", "model", name=op.f("pk_chunk_embeddings")),
    )
    op.create_index(
        "ix_chunk_embeddings_hnsw",
        "chunk_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "run_steps",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("agent_name", sa.String(length=40), nullable=True),
        sa.Column("model_used", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tokens_in", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cost_eur",
            sa.Numeric(precision=12, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_steps_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
        sa.UniqueConstraint("run_id", "seq", name="uq_run_steps_run_seq"),
    )
    op.create_table(
        "tool_invocations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("policy_decision", sa.String(length=16), nullable=False),
        sa.Column("decision_reason", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "policy_decision IN ('allow','confirm','deny')",
            name=op.f("ck_tool_invocations_policy_decision_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_tool_invocations_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["run_steps.id"],
            name=op.f("fk_tool_invocations_step_id_run_steps"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_invocations")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_tool_invocations_idempotency_key")),
    )
    op.create_index(
        op.f("ix_tool_invocations_run_id"), "tool_invocations", ["run_id"], unique=False
    )
    op.create_table(
        "pending_actions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("invocation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("preview", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("nonce", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response", sa.String(length=16), nullable=True),
        sa.Column("responded_via", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "responded_via IS NULL OR responded_via IN ('ui','voice','gesture')",
            name=op.f("ck_pending_actions_responded_via_valid"),
        ),
        sa.CheckConstraint(
            "response IS NULL OR response IN ('approved','rejected','expired')",
            name=op.f("ck_pending_actions_response_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["invocation_id"],
            ["tool_invocations.id"],
            name=op.f("fk_pending_actions_invocation_id_tool_invocations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pending_actions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_actions")),
        sa.UniqueConstraint("invocation_id", name=op.f("uq_pending_actions_invocation_id")),
    )
    op.create_index(
        op.f("ix_pending_actions_user_id"), "pending_actions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_pending_open",
        "pending_actions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("response IS NULL"),
    )
    # ### end Alembic commands ###

    # --------------------------------------------------------------------
    # Unveränderlichkeit des Audit-Logs auf Datenbankebene.
    #
    # Die Zusicherung darf nicht von Anwendungsdisziplin abhängen. Ein Trigger
    # verhindert UPDATE und DELETE auch für den Tabelleneigentümer — ein reines
    # REVOKE griffe dort nicht.
    # --------------------------------------------------------------------
    # Genau eine Ausnahme ist zugelassen: das Nullen von user_id bei sonst
    # unveraenderter Zeile. Ohne sie waere die Nutzerloeschung (Art. 17 DSGVO)
    # unmoeglich, weil das ON DELETE SET NULL der Fremdschluesselbeziehung
    # selbst ein UPDATE ist.
    #
    # Das ist unbedenklich, weil entry_hash ueber den kanonisierten Eintrag
    # OHNE user_id gebildet wird — die Pseudonymisierung laesst die Hash-Kette
    # damit intakt. Wird diese Regel in der Anwendung geaendert, muss dieser
    # Trigger mitgeaendert werden.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_is_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            IF TG_OP = 'UPDATE'
               AND OLD.user_id IS NOT NULL
               AND NEW.user_id IS NULL
               AND NEW.id           =  OLD.id
               AND NEW.occurred_at  =  OLD.occurred_at
               AND NEW.actor        =  OLD.actor
               AND NEW.action       =  OLD.action
               AND NEW.details      =  OLD.details
               AND NEW.entry_hash   =  OLD.entry_hash
               AND NEW.resource  IS NOT DISTINCT FROM OLD.resource
               AND NEW.trace_id  IS NOT DISTINCT FROM OLD.trace_id
               AND NEW.prev_hash IS NOT DISTINCT FROM OLD.prev_hash
            THEN
                RETURN NEW;  -- zulaessige Pseudonymisierung
            END IF;

            RAISE EXCEPTION 'audit_log ist append-only: % ist nicht zulaessig', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_is_append_only();
        """
    )
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON audit_log FROM PUBLIC")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_is_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_pending_open",
        table_name="pending_actions",
        postgresql_where=sa.text("response IS NULL"),
    )
    op.drop_index(op.f("ix_pending_actions_user_id"), table_name="pending_actions")
    op.drop_table("pending_actions")
    op.drop_index(op.f("ix_tool_invocations_run_id"), table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_table("run_steps")
    op.drop_index(
        "ix_chunk_embeddings_hnsw",
        table_name="chunk_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("chunk_embeddings")
    op.drop_index("ix_runs_user_started", table_name="runs")
    op.drop_index(op.f("ix_runs_trace_id"), table_name="runs")
    op.drop_index(
        "ix_runs_resumable",
        table_name="runs",
        postgresql_where=sa.text(
            "status IN ('queued','planning','executing','awaiting_confirmation')"
        ),
    )
    op.drop_table("runs")
    op.drop_index(op.f("ix_oauth_credentials_created_at"), table_name="oauth_credentials")
    op.drop_index(op.f("ix_oauth_credentials_account_id"), table_name="oauth_credentials")
    op.drop_table("oauth_credentials")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "ix_memory_embeddings_hnsw",
        table_name="memory_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("memory_embeddings")
    op.drop_index("ix_chunks_search_tsv", table_name="document_chunks", postgresql_using="gin")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_webauthn_credentials_user_id"), table_name="webauthn_credentials")
    op.drop_index(op.f("ix_webauthn_credentials_created_at"), table_name="webauthn_credentials")
    op.drop_table("webauthn_credentials")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_due_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_at"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("plugin_permissions")
    op.drop_index(op.f("ix_permissions_created_at"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index("ix_memories_user_kind_status", table_name="memories")
    op.drop_index("ix_memories_search_tsv", table_name="memories", postgresql_using="gin")
    op.drop_index(
        "ix_memories_retention",
        table_name="memories",
        postgresql_where=sa.text("retention_until IS NOT NULL"),
    )
    op.drop_index(op.f("ix_memories_created_at"), table_name="memories")
    op.drop_table("memories")
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_created_at"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_connected_accounts_created_at"), table_name="connected_accounts")
    op.drop_table("connected_accounts")
    op.drop_index(
        "ix_automations_next_fire", table_name="automations", postgresql_where=sa.text("enabled")
    )
    op.drop_index(op.f("ix_automations_created_at"), table_name="automations")
    op.drop_table("automations")
    op.drop_index(op.f("ix_audit_log_occurred_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_table("system_health")
    op.drop_table("scopes")
    op.drop_index(op.f("ix_plugins_created_at"), table_name="plugins")
    op.drop_table("plugins")
    # ### end Alembic commands ###
