"""approval binding: payload hash, session, channel

Revision ID: 0cbbf443114a
Revises: b69b65ba012c
Erstellt: 2026-08-18 18:44:43.061327
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0cbbf443114a"
down_revision: str | None = "b69b65ba012c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pending_actions", sa.Column("payload_hash", sa.String(length=64), nullable=False)
    )
    op.add_column(
        "pending_actions",
        sa.Column("frozen_arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("pending_actions", sa.Column("run_id", sa.UUID(), nullable=False))
    op.add_column("pending_actions", sa.Column("session_id", sa.UUID(), nullable=False))
    op.add_column(
        "pending_actions", sa.Column("requested_channel", sa.String(length=10), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_pending_actions_run_id_runs"),
        "pending_actions",
        "runs",
        ["run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_check_constraint(
        op.f("ck_pending_actions_nonce_min_entropy"), "pending_actions", "length(nonce) >= 32"
    )
    op.create_check_constraint(
        op.f("ck_pending_actions_payload_hash_format"),
        "pending_actions",
        "payload_hash ~ '^[0-9a-f]{64}$'",
    )
    op.create_check_constraint(
        op.f("ck_pending_actions_requested_channel_valid"),
        "pending_actions",
        "requested_channel IN ('ui','voice','gesture')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_pending_actions_requested_channel_valid"), "pending_actions", type_="check"
    )
    op.drop_constraint(
        op.f("ck_pending_actions_payload_hash_format"), "pending_actions", type_="check"
    )
    op.drop_constraint(
        op.f("ck_pending_actions_nonce_min_entropy"), "pending_actions", type_="check"
    )
    op.drop_constraint(
        op.f("fk_pending_actions_run_id_runs"), "pending_actions", type_="foreignkey"
    )
    op.drop_column("pending_actions", "requested_channel")
    op.drop_column("pending_actions", "session_id")
    op.drop_column("pending_actions", "run_id")
    op.drop_column("pending_actions", "frozen_arguments")
    op.drop_column("pending_actions", "payload_hash")
    # ### end Alembic commands ###
