"""pending_actions tool_name

Revision ID: 28cadea459be
Revises: 0cbbf443114a
Erstellt: 2026-08-18 18:52:25.504475
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "28cadea459be"
down_revision: str | None = "0cbbf443114a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pending_actions", sa.Column("tool_name", sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pending_actions", "tool_name")
    # ### end Alembic commands ###
