"""execution claim

Revision ID: 6a5d644b25a2
Revises: 9768b6f23128
Erstellt: 2026-08-19 10:52:57.710850
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6a5d644b25a2"
down_revision: str | None = "9768b6f23128"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pending_actions", sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pending_actions", "executed_at")
    # ### end Alembic commands ###
