"""webauthn challenges

Revision ID: 9768b6f23128
Revises: fc5956228af1
Erstellt: 2026-08-19 00:09:59.539467
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9768b6f23128"
down_revision: str | None = "fc5956228af1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webauthn_challenges",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("value", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('registration','authentication')",
            name=op.f("ck_webauthn_challenges_challenge_purpose_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_webauthn_challenges_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webauthn_challenges")),
        sa.UniqueConstraint("value", name=op.f("uq_webauthn_challenges_value")),
    )
    op.create_index(
        "ix_challenges_open",
        "webauthn_challenges",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_challenges_open",
        table_name="webauthn_challenges",
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.drop_table("webauthn_challenges")
    # ### end Alembic commands ###
