"""v1.1 identity, goals, entities, taint sanitization

Revision ID: b69b65ba012c
Revises: 07215b957d0f
Erstellt: 2026-08-18 17:10:24.413891
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b69b65ba012c"
down_revision: str | None = "07215b957d0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "behaviour_rules",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("rule", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=24), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('do','dont')", name=op.f("ck_behaviour_rules_kind_valid")),
        sa.CheckConstraint(
            "priority BETWEEN 1 AND 5", name=op.f("ck_behaviour_rules_priority_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_behaviour_rules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_behaviour_rules")),
    )
    op.create_index(
        op.f("ix_behaviour_rules_created_at"), "behaviour_rules", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_behaviour_rules_user_id"), "behaviour_rules", ["user_id"], unique=False
    )
    op.create_table(
        "domain_preferences",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=24), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), server_default=sa.text("1.0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_domain_preferences_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_domain_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_preferences")),
        sa.UniqueConstraint("user_id", "domain", "key", name="uq_domain_pref"),
    )
    op.create_index(
        op.f("ix_domain_preferences_created_at"), "domain_preferences", ["created_at"], unique=False
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("horizon", sa.String(length=12), server_default="offen", nullable=False),
        sa.Column("status", sa.String(length=12), server_default="aktiv", nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "constraints",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("progress_note", sa.Text(), nullable=True),
        sa.Column("data_class", sa.String(length=2), server_default="P2", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('german', title || ' ' || coalesce(description, ''))", persisted=True
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_class IN ('P0','P1','P2','P3')", name=op.f("ck_goals_data_class_valid")
        ),
        sa.CheckConstraint(
            "horizon IN ('tag','woche','monat','quartal','jahr','offen')",
            name=op.f("ck_goals_horizon_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'erreicht' OR completed_at IS NOT NULL",
            name=op.f("ck_goals_completed_needs_date"),
        ),
        sa.CheckConstraint(
            "status IN ('aktiv','pausiert','erreicht','verworfen')",
            name=op.f("ck_goals_status_valid"),
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_goals_no_self_parent")
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_goals_priority_range")),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["goals.id"], name=op.f("fk_goals_parent_id_goals"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    op.create_index(op.f("ix_goals_created_at"), "goals", ["created_at"], unique=False)
    op.create_index(
        "ix_goals_search_tsv", "goals", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_goals_user_status", "goals", ["user_id", "status"], unique=False)
    op.create_table(
        "entities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column(
            "aliases",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("gender", sa.String(length=8), server_default="unknown", nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("data_class", sa.String(length=2), server_default="P2", nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=True),
        sa.Column("last_mentioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mention_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_class IN ('P0','P1','P2','P3')", name=op.f("ck_entities_data_class_valid")
        ),
        sa.CheckConstraint(
            "gender IN ('m','f','n','unknown')", name=op.f("ck_entities_gender_valid")
        ),
        sa.CheckConstraint(
            "kind <> 'goal' OR goal_id IS NOT NULL", name=op.f("ck_entities_goal_kind_needs_goal")
        ),
        sa.CheckConstraint(
            "kind IN ('person','organisation','projekt','ort','goal','thema')",
            name=op.f("ck_entities_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"], ["goals.id"], name=op.f("fk_entities_goal_id_goals"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_entities_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint("user_id", "kind", "canonical_name", name="uq_entity_identity"),
    )
    op.create_index(
        "ix_entities_aliases", "entities", ["aliases"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_entities_created_at"), "entities", ["created_at"], unique=False)
    op.create_index(
        "ix_entities_salience", "entities", ["user_id", "last_mentioned_at"], unique=False
    )
    op.create_index("ix_entities_user_kind", "entities", ["user_id", "kind"], unique=False)
    op.create_table(
        "entity_links",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("target_kind", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=60), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_kind IN ('memory','document','task','goal','message','event')",
            name=op.f("ck_entity_links_target_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_links_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "entity_id", "target_kind", "target_id", name=op.f("pk_entity_links")
        ),
    )
    op.create_index(
        "ix_entity_links_target", "entity_links", ["target_kind", "target_id"], unique=False
    )
    op.create_table(
        "entity_relations",
        sa.Column("from_entity_id", sa.UUID(), nullable=False),
        sa.Column("to_entity_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=60), nullable=False),
        sa.Column("confidence", sa.Float(), server_default=sa.text("1.0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_entity_relations_confidence_range")
        ),
        sa.CheckConstraint(
            "from_entity_id <> to_entity_id", name=op.f("ck_entity_relations_no_self_relation")
        ),
        sa.ForeignKeyConstraint(
            ["from_entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_relations_from_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_relations_to_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "from_entity_id", "to_entity_id", "relation", name=op.f("pk_entity_relations")
        ),
    )
    op.add_column("runs", sa.Column("sanitized_from_run_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_runs_sanitized_from_run_id_runs"),
        "runs",
        "runs",
        ["sanitized_from_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        op.f("ck_runs_sanitized_runs_are_clean"),
        "runs",
        "sanitized_from_run_id IS NULL OR taint_level = 'clean'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_runs_sanitized_runs_are_clean"), "runs", type_="check")
    op.drop_constraint(op.f("fk_runs_sanitized_from_run_id_runs"), "runs", type_="foreignkey")
    op.drop_column("runs", "sanitized_from_run_id")
    op.drop_table("entity_relations")
    op.drop_index("ix_entity_links_target", table_name="entity_links")
    op.drop_table("entity_links")
    op.drop_index("ix_entities_user_kind", table_name="entities")
    op.drop_index("ix_entities_salience", table_name="entities")
    op.drop_index(op.f("ix_entities_created_at"), table_name="entities")
    op.drop_index("ix_entities_aliases", table_name="entities", postgresql_using="gin")
    op.drop_table("entities")
    op.drop_index("ix_goals_user_status", table_name="goals")
    op.drop_index("ix_goals_search_tsv", table_name="goals", postgresql_using="gin")
    op.drop_index(op.f("ix_goals_created_at"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_domain_preferences_created_at"), table_name="domain_preferences")
    op.drop_table("domain_preferences")
    op.drop_index(op.f("ix_behaviour_rules_user_id"), table_name="behaviour_rules")
    op.drop_index(op.f("ix_behaviour_rules_created_at"), table_name="behaviour_rules")
    op.drop_table("behaviour_rules")
    # ### end Alembic commands ###
