"""sessions — echte Anmeldung statt durchgereichter UUID

Bis hierher war ``session_id`` ein Wert, den der Aufrufer mitbrachte. Die
Sitzungsbindung einer Bestätigung (``approval-channel-bound``) prüfte damit
nur, ob zwei UUIDs übereinstimmen. Diese Tabelle macht daraus eine
Zusicherung.

Gespeichert wird der **Hash** des Tokens, nie der Token selbst: Wer die
Tabelle zu sehen bekommt, soll sich damit nicht anmelden können.

Revision ID: fc5956228af1
Revises: 28cadea459be
Erstellt: 2026-08-18 23:58:52.926859
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fc5956228af1"
down_revision: str | None = "28cadea459be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("client", sa.String(length=200), server_default="", nullable=False),
        sa.Column("channel", sa.String(length=16), server_default="ui", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "channel IN ('ui','voice','edge')", name=op.f("ck_sessions_session_channel_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(
        "ix_sessions_active",
        "sessions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(
        "ix_sessions_active", table_name="sessions", postgresql_where=sa.text("revoked_at IS NULL")
    )
    op.drop_table("sessions")
    # ### end Alembic commands ###
