"""jarvis_contracts — die einzige Quelle der Wahrheit für alle Typen.

Dieses Paket importiert *nichts* aus dem übrigen Projekt. Aus ihm werden
OpenAPI-Schema, TypeScript-Typen und Zod-Schemata generiert (siehe
docs/02-repo-struktur.md §3).
"""

from __future__ import annotations

from .agents import AgentRequest, AgentResult, AgentSpec, AgentStatus
from .auth import (
    DEFAULT_CHALLENGE_TTL,
    DEFAULT_IDLE_TIMEOUT,
    DEFAULT_SESSION_TTL,
    ChallengePurpose,
    IssuedSession,
    PasskeyCredential,
    Session,
    WebAuthnChallenge,
)
from .classification import DataClass, TaintLevel, escalate
from .context import (
    CONTEXT_BUDGETS,
    ContextBundle,
    ContextCost,
    ContextFragment,
    ContextPriority,
    ContextRequest,
    ReferenceResolution,
    SalientEntity,
)
from .errors import ErrorCode, JarvisError, Problem, Remediation
from .events import (
    ActionResolved,
    ActionWaiting,
    CameraState,
    ClientMessage,
    CoreState,
    HealthEntry,
    InterruptKind,
    MicState,
    RunFinished,
    RunStarted,
    ServerMessage,
    StepFinished,
    TokenDelta,
)
from .goals import (
    Entity,
    EntityKind,
    EntityLink,
    EntityRelation,
    Goal,
    GoalHorizon,
    GoalProgress,
    GoalStatus,
)
from .identity import (
    CORE_PROFILE_TOKEN_BUDGET,
    BehaviourRule,
    CoreProfile,
    DomainPreference,
    Formality,
    PreferenceDomain,
    Proactivity,
    ResponseLength,
)
from .llm import (
    CompletionRequest,
    CompletionResult,
    FinishReason,
    Message,
    MessageRole,
    ModelUsage,
    ProposedToolCall,
    ProviderCapabilities,
    StreamChunk,
)
from .memory import (
    DEFAULT_RETRIEVAL_WEIGHTS,
    MemoryCandidate,
    MemoryHit,
    MemoryKind,
    MemoryQuery,
    MemoryRecord,
    MemoryStatus,
    Provenance,
    RetrievalWeights,
    SourceType,
)
from .permissions import (
    CONSTRAINTS_BY_SCOPE,
    SENSITIVE_FILE_PATTERNS,
    ActionPreview,
    AmountConstraints,
    ApprovalChannel,
    ConstraintViolation,
    FilesConstraints,
    MailSendConstraints,
    PendingAction,
    PermissionGrant,
    PermissionMode,
    PolicyDecision,
    PolicyEffect,
    PolicyRequest,
    PreviewField,
    RiskLevel,
    ScopeConstraints,
    ScopeSpec,
    TimeWindow,
    WebConstraints,
    constraints_for,
    is_sensitive_filename,
)
from .run_state import Correction, RunState, StepOutcome
from .runs import (
    BUDGET_PRESETS,
    Capability,
    Complexity,
    DailySpend,
    Intent,
    ModelCapability,
    Plan,
    PlanStep,
    RoutingDecision,
    Run,
    RunBudget,
    RunStatus,
    RunStep,
    RunTrigger,
    TurnClassification,
    Usage,
)
from .tools import (
    UNDO_TTL,
    InvocationStatus,
    PayloadInspectability,
    SanitizedPayload,
    Source,
    TaintGateOutcome,
    ToolInvocation,
    ToolResult,
    ToolSpec,
    mit_hinweisen,
)

__version__ = "0.1.0"

__all__ = [  # noqa: RUF022 — bewusst nach Modulen gruppiert, nicht alphabetisch
    "__version__",
    # classification
    "DataClass",
    "TaintLevel",
    "escalate",
    # auth
    "Session",
    "IssuedSession",
    "WebAuthnChallenge",
    "ChallengePurpose",
    "PasskeyCredential",
    "DEFAULT_SESSION_TTL",
    "DEFAULT_IDLE_TIMEOUT",
    "DEFAULT_CHALLENGE_TTL",
    # llm
    "Message",
    "MessageRole",
    "ProposedToolCall",
    "CompletionRequest",
    "CompletionResult",
    "StreamChunk",
    "FinishReason",
    "ModelUsage",
    "ProviderCapabilities",
    # permissions
    "ApprovalChannel",
    "RiskLevel",
    "PermissionMode",
    "PolicyEffect",
    "ScopeSpec",
    "TimeWindow",
    "ScopeConstraints",
    "MailSendConstraints",
    "FilesConstraints",
    "WebConstraints",
    "CONSTRAINTS_BY_SCOPE",
    "SENSITIVE_FILE_PATTERNS",
    "is_sensitive_filename",
    "AmountConstraints",
    "constraints_for",
    "mit_hinweisen",
    "ConstraintViolation",
    "PermissionGrant",
    "PolicyRequest",
    "PolicyDecision",
    "ActionPreview",
    "PreviewField",
    "PendingAction",
    # tools
    "PayloadInspectability",
    "TaintGateOutcome",
    "SanitizedPayload",
    "ToolSpec",
    "ToolResult",
    "UNDO_TTL",
    "ToolInvocation",
    "InvocationStatus",
    "Source",
    # runs
    "RunState",
    "StepOutcome",
    "Correction",
    "RunStatus",
    "RunTrigger",
    "Intent",
    "Complexity",
    "DailySpend",
    "Capability",
    "TurnClassification",
    "RunBudget",
    "Usage",
    "PlanStep",
    "Plan",
    "RoutingDecision",
    "ModelCapability",
    "RunStep",
    "Run",
    "BUDGET_PRESETS",
    # memory
    "MemoryKind",
    "MemoryStatus",
    "SourceType",
    "Provenance",
    "MemoryRecord",
    "MemoryCandidate",
    "MemoryQuery",
    "MemoryHit",
    "RetrievalWeights",
    "DEFAULT_RETRIEVAL_WEIGHTS",
    # context
    "ContextCost",
    "ContextPriority",
    "ContextFragment",
    "ContextRequest",
    "ContextBundle",
    "SalientEntity",
    "ReferenceResolution",
    "CONTEXT_BUDGETS",
    # agents
    "AgentSpec",
    "AgentRequest",
    "AgentResult",
    "AgentStatus",
    # events
    "InterruptKind",
    "CoreState",
    "MicState",
    "CameraState",
    "ClientMessage",
    "ActionResolved",
    "ActionWaiting",
    "RunFinished",
    "RunStarted",
    "ServerMessage",
    "StepFinished",
    "TokenDelta",
    "HealthEntry",
    # identity & preferences (V1.1)
    "CoreProfile",
    "DomainPreference",
    "BehaviourRule",
    "Formality",
    "ResponseLength",
    "Proactivity",
    "PreferenceDomain",
    "CORE_PROFILE_TOKEN_BUDGET",
    # goals & entities (V1.1)
    "Goal",
    "GoalHorizon",
    "GoalStatus",
    "GoalProgress",
    "Entity",
    "EntityKind",
    "EntityLink",
    "EntityRelation",
    # errors
    "ErrorCode",
    "Remediation",
    "Problem",
    "JarvisError",
]
